name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 103.178.153.249
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Buat folder jika belum ada, lalu masuk
            mkdir -p /var/www/html/uassisop
            cd /var/www/html/uassisop
            
            # Jika belum ada git, inisialisasi dan ambil kodenya
            if [ ! -d ".git" ]; then
              git clone https://github.com/tiaeryanti/uassisop.git .
            else
              git pull origin main
            fi
            
            # Jalankan docker jika ada konfigurasinya
            if [ -f "docker-compose.yml" ]; then
              docker compose pull
              docker compose up -d
            fi
